from enum import Enum


class Gender(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class BookingSource(str, Enum):
    ONLINE = "ONLINE"
    FRONTDESK = "FRONTDESK"
    WALKIN = "WALKIN"


class SlotStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    BOOKED = "BOOKED"
    CANCELLED_BY_DOCTOR = "CANCELLED_BY_DOCTOR"
    BLOCKED = "BLOCKED"


class AppointmentStatus(str, Enum):
    BOOKED = "BOOKED"
    COMPLETED = "COMPLETED"
    CANCELLED_BY_PATIENT = "CANCELLED_BY_PATIENT"
    CANCELLED_BY_FRONTDESK = "CANCELLED_BY_FRONTDESK"
    CANCELLED_BY_DOCTOR = "CANCELLED_BY_DOCTOR"
    NO_SHOW = "NO_SHOW"


class ContactStatus(str, Enum):
    NEW = "NEW"
    IN_PROGRESS = "IN_PROGRESS"
    CLOSED = "CLOSED"


class WaitingStatus(str, Enum):
    WAITING = "WAITING"
    NOTIFIED = "NOTIFIED"
    CONFIRMED = "CONFIRMED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class OTPPurpose(str, Enum):
    BOOK_APPOINTMENT = "BOOK_APPOINTMENT"
    VIEW_PRESCRIPTION = "VIEW_PRESCRIPTION"
    PASSWORD_RESET = "PASSWORD_RESET"


class WalkInStatus(str, Enum):
    WAITING = "WAITING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class OTPStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    EXPIRED = "EXPIRED"


class NotificationType(str, Enum):
    APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED"
    DOCTOR_EMERGENCY = "DOCTOR_EMERGENCY"
    NEW_CONTACT_REQUEST = "NEW_CONTACT_REQUEST"
    FOLLOW_UP_REMINDER = "FOLLOW_UP_REMINDER"
    WAITING_LIST_AVAILABLE = "WAITING_LIST_AVAILABLE"
