"""Describe your change

Revision ID: cb4b8f41fd21
Revises: a0412ea68513
Create Date: 2026-07-28 09:08:53.564935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb4b8f41fd21'
down_revision: Union[str, Sequence[str], None] = 'a0412ea68513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'appointment_status',
               existing_type=postgresql.ENUM('BOOKED', 'COMPLETED', 'CANCELLED_BY_PATIENT', 'CANCELLED_BY_FRONTDESK', 'CANCELLED_BY_DOCTOR', 'NO_SHOW', name='appointment_status'),
               nullable=False,
               existing_server_default=sa.text("'BOOKED'::appointment_status"))
    op.alter_column('clinic_settings', 'slot_generation_done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contact_queries', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'CLOSED', name='contact_status'),
               nullable=False,
               existing_server_default=sa.text("'NEW'::contact_status"))
    op.alter_column('doctor_availability', 'slot_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'BOOKED', 'CANCELLED_BY_DOCTOR', 'BLOCKED', name='slot_status'),
               nullable=False,
               existing_server_default=sa.text("'AVAILABLE'::slot_status"))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('otp_verifications', 'attempt_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('otp_verifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'EXPIRED', name='otp_status'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::otp_status"))
    op.alter_column('prescriptions', 'follow_up_reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', name='user_status'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::user_status"))
    op.alter_column('waiting_list', 'status',
               existing_type=postgresql.ENUM('WAITING', 'NOTIFIED', 'CONFIRMED', 'EXPIRED', 'CANCELLED', name='waiting_status'),
               nullable=False,
               existing_server_default=sa.text("'WAITING'::waiting_status"))
    op.alter_column('walk_in_tokens', 'status',
               existing_type=postgresql.ENUM('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='walk_in_status'),
               nullable=False,
               existing_server_default=sa.text("'WAITING'::walk_in_status"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('walk_in_tokens', 'status',
               existing_type=postgresql.ENUM('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='walk_in_status'),
               nullable=True,
               existing_server_default=sa.text("'WAITING'::walk_in_status"))
    op.alter_column('waiting_list', 'status',
               existing_type=postgresql.ENUM('WAITING', 'NOTIFIED', 'CONFIRMED', 'EXPIRED', 'CANCELLED', name='waiting_status'),
               nullable=True,
               existing_server_default=sa.text("'WAITING'::waiting_status"))
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', name='user_status'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::user_status"))
    op.alter_column('prescriptions', 'follow_up_reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('otp_verifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'EXPIRED', name='otp_status'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::otp_status"))
    op.alter_column('otp_verifications', 'attempt_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('doctor_availability', 'slot_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'BOOKED', 'CANCELLED_BY_DOCTOR', 'BLOCKED', name='slot_status'),
               nullable=True,
               existing_server_default=sa.text("'AVAILABLE'::slot_status"))
    op.alter_column('contact_queries', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'CLOSED', name='contact_status'),
               nullable=True,
               existing_server_default=sa.text("'NEW'::contact_status"))
    op.alter_column('clinic_settings', 'slot_generation_done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'appointment_status',
               existing_type=postgresql.ENUM('BOOKED', 'COMPLETED', 'CANCELLED_BY_PATIENT', 'CANCELLED_BY_FRONTDESK', 'CANCELLED_BY_DOCTOR', 'NO_SHOW', name='appointment_status'),
               nullable=True,
               existing_server_default=sa.text("'BOOKED'::appointment_status"))
    # ### end Alembic commands ###
